name: test

on: # test any PRs and master development branch changes
  pull_request:
  push:
    branches:
      - master

jobs:
  test: # make sure the action works
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Replace action versions with master
        run: |
          sed -i 's/nxtlvlsoftware\/\([-|a-zA-Z0-9]*\)@v\([0-9]*\(\.[0-9]\)\{0,2\}\)/nxtlvlsoftware\/\1@master/g' ./action.yml
      - name: Run action against test plugin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: ./
        with:
          analyse: ./tests/actions_test_plugin/src
          level: 9
          config: ./pocketmine/phpstan/strict.phpstan.neon.dist
          no-progress: false